# Generated by Django 2.2 on 2020-06-27 17:41

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Automatically created from category name for product page URL.', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords for meta tag, should be comma-delimited', max_length=255)),
                ('meta_description', models.CharField(blank=True, help_text='Short and to the point content for description meta tag', max_length=255)),
                ('meta_title', models.CharField(blank=True, help_text='Title meta tag', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Automatically created from category name for product page URL.', max_length=255, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('product_code', models.CharField(max_length=6, unique=True)),
                ('main_image', models.ImageField(upload_to='product_images/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_description', models.CharField(help_text='Short and to the point content for description meta tag', max_length=255)),
                ('meta_keywords', models.CharField(help_text='SEO keywords for meta tag, should be comma-delimited', max_length=255)),
                ('meta_title', models.CharField(help_text='Title meta tag', max_length=255)),
                ('is_new', models.BooleanField(default=True)),
                ('youtube_url', models.URLField(blank=True, max_length=255)),
                ('kg_weight', models.DecimalField(decimal_places=2, default=0.0, help_text='Only for delivery purposes', max_digits=6)),
                ('is_on_promotion', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='FileManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_file', models.FileField(upload_to='product_files/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name_plural': 'File Manager',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristics', models.CharField(choices=[('size', 'Size'), ('color', 'Color'), ('age', 'Age')], default=None, max_length=50)),
                ('value', models.CharField(blank=True, max_length=50)),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
